-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Hostiteľ: 131.153.158.88
-- Čas generovania: Št 18.Jún 2026, 13:08
-- Verzia serveru: 8.0.35
-- Verzia PHP: 8.4.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Databáza: `yl3njzb_zcfo`
--

-- --------------------------------------------------------

--
-- Štruktúra tabuľky pre tabuľku `wp_Ekupa97M_motionpage_code`
--

CREATE TABLE `wp_Ekupa97M_motionpage_code` (
  `id` bigint UNSIGNED NOT NULL,
  `script_value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_id` bigint DEFAULT NULL,
  `is_global` tinyint(1) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `plugins` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `types` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `cats` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `data_id` bigint UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Sťahujem dáta pre tabuľku `wp_Ekupa97M_motionpage_code`
--

INSERT INTO `wp_Ekupa97M_motionpage_code` (`id`, `script_value`, `post_id`, `is_global`, `is_active`, `plugins`, `types`, `cats`, `data_id`) VALUES
(1, 'window._mp_sequence_FGchFglHKzKeuxzqk=new _mp_ImageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/e479l78/\",ext:\"webp\",totalFrames:141,skipFrames:2,timelineUID:\"_mp_1678280599\",imgBreakpoints:{small:576,medium:768}});window._mp_1678280599=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1.1,timeSlide2:2.2,timeSlide3:3.5},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause();', 2897, 0, 1, 'ImageSequence,BypassReducedMotion', '', '', 1),
(2, '_$W._mp_1685807214_CTX=gsap.context(()=>{_$W._mp_1685807214=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",numSlides:3,timeSlide1:1.1,timeSlide2:2.2,timeSlide3:3.5,data:{numSlides:3,timeSlide1:1.1,timeSlide2:2.2,timeSlide3:3.5},duration:4},0).yoyo(!0).repeat(-1)});', 6432, 0, 1, 'BypassReducedMotion', '', '', 2),
(3, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/3cdhm5j/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702044797\",totalFrames:212,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702044797_CTX=gsap.context(()=>{_$W._mp_1702044797=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:4,timeSlide1:.6,timeSlide2:1.35,timeSlide3:2.7,timeSlide4:3.8},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4687, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/mkh-en/,/system-uzavretych-vodicov-mkh/', 3),
(5, 'window._mp_sequence_KEHGVXDWEWGWZGDC = new window.MOTIONPAGE_FRONT.imageSequence({\"id\":\"KEHGVXDWEWGWZGDC\",\"canvasSelector\":\"#mpAnimation\",\"largeImagesRoot\":\"https://s-d-a.tech/wp-content/uploads/sequence/i5e39g3/\",\"ext\":\"webp\",\"totalFrames\":141,\"skipFrames\":2,\"timelineUID\":\"_mp_1702311923\",\"dpr\":1.25});addEventListener(\"load\",e => {_$W._mp_1702311923_CTX=gsap.context(()=>{_$W._mp_1702311923=gsap.timeline().from(\"#mpAnimation\",{numSlides:3,timeSlide1:1.1,timeSlide2:2.2,timeSlide3:3.5,data:{numSlides:3,timeSlide1:1.1,timeSlide2:2.2,timeSlide3:3.5},onUpdate:function(){let s=_mp_sequence_KEHGVXDWEWGWZGDC;s&&\"handleUpdate\"in s&&s.handleUpdate(this.progress())},duration:4},0).yoyo(!0).repeat(-1).pause()});});', 4657, 0, 1, 'ImageSequence,BypassReducedMotion', '', '', 5),
(6, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/la6aeih/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702312396\",totalFrames:141,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702312396_CTX=gsap.context(()=>{_$W._mp_1702312396=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1,timeSlide2:2,timeSlide3:3.8},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4627, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/izolovane-systemy-u10-faba100/', 6),
(7, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/i2755fh/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702463476\",totalFrames:141,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702463476_CTX=gsap.context(()=>{_$W._mp_1702463476=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1,timeSlide2:2,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4645, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/insulated-u15-en/,/izolovane-systemy-u15-u25-u35/', 7),
(8, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/2dc4dhj/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702464273\",totalFrames:141,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702464273_CTX=gsap.context(()=>{_$W._mp_1702464273=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1,timeSlide2:2,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4651, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/insulated-u20-en/,/izolovane-systemy-u20-u30/', 8),
(9, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/kg885a8/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702465111\",totalFrames:290,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702465111_CTX=gsap.context(()=>{_$W._mp_1702465111=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:5,timeSlide1:.5,timeSlide2:1.3,timeSlide3:2.5,timeSlide4:3.75,timeSlide5:4.8},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:5},0).yoyo(!0).repeat(-1).pause()});', 4669, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/vcl-en/,/kompaktny-vodicovy-system-vcl/', 9),
(10, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/18b2iib/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702466691\",totalFrames:141,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702466691_CTX=gsap.context(()=>{_$W._mp_1702466691=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:.9,timeSlide2:2.1,timeSlide3:3.8},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4675, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/vks-en/,/kompaktny-vodicovy-system-vks/', 10),
(11, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/9ge39he/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702467039\",totalFrames:141,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702467039_CTX=gsap.context(()=>{_$W._mp_1702467039=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1,timeSlide2:2.05,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4663, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/vks10-en/,/kompaktny-vodicovy-system-vks10/', 11),
(12, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/dcbdibc/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702811009\",totalFrames:212,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702811009_CTX=gsap.context(()=>{_$W._mp_1702811009=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:4,timeSlide1:.6,timeSlide2:1.3,timeSlide3:2.5,timeSlide4:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4681, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/kbh-en/,/system-uzavretych-vodicov-kbh/', 12),
(13, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/h5c5j87/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702811602\",totalFrames:141,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702811602_CTX=gsap.context(()=>{_$W._mp_1702811602=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1,timeSlide2:2.1,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4694, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/lsv-en/,/system-uzavretych-vodicov-lsv-lsvg/', 13),
(14, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/1eaah27/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702812516\",totalFrames:176,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702812516_CTX=gsap.context(()=>{_$W._mp_1702812516=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:2,timeSlide1:2.5,timeSlide2:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4700, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/large-festoon-en/,/velke-festonove-systemy/', 14),
(15, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/0305b62/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702812863\",totalFrames:176,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702812863_CTX=gsap.context(()=>{_$W._mp_1702812863=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:2,timeSlide1:2.5,timeSlide2:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4706, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/small-festoon-en/,/male-festonove-systemy/', 15),
(16, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/c2jdk87/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702813178\",totalFrames:313,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702813178_CTX=gsap.context(()=>{_$W._mp_1702813178=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1.5,timeSlide2:3,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4712, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/motor-powered-cable-en/,/motorom-pohanane-kablove-navijaky/', 16),
(17, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/f9b289b/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702813485\",totalFrames:184,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702813485_CTX=gsap.context(()=>{_$W._mp_1702813485=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1.5,timeSlide2:3,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4755, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/spring-powered-cable-en/,/pruzinove-kablove-navijaky/', 17),
(18, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/f7ehfd4/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702818639\",totalFrames:166,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702818639_CTX=gsap.context(()=>{_$W._mp_1702818639=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:.8,timeSlide2:2.4,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4761, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/cps-140khz-en/,/cps-140khz-sk/', 18),
(19, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/am12gbk/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702828411\",totalFrames:166,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702828411_CTX=gsap.context(()=>{_$W._mp_1702828411=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:.8,timeSlide2:2.4,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4767, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/cps-20khz-en/,/cps-20khz-sk/', 19),
(20, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/fded9m4/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702848406\",totalFrames:141,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702848406_CTX=gsap.context(()=>{_$W._mp_1702848406=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1,timeSlide2:2.6,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4773, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/charging-contacts-en/', 20),
(21, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/j6gmg3l/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702848609\",totalFrames:205,frames:[1,204],imgBreakpoints:{small:576,medium:768}});_$W._mp_1702848609_CTX=gsap.context(()=>{_$W._mp_1702848609=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:.7,timeSlide2:1.8,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4782, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/shuttle-charging-system-en/,/system-kyvadloveho-nabijania/', 21),
(22, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/29fad74/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702897230\",totalFrames:276,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702897230_CTX=gsap.context(()=>{_$W._mp_1702897230=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:.5,timeSlide2:1.8,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4788, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/smgx-en/,/slotted-microwave-guide-sk/', 22),
(23, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/9f2l3if/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702897807\",totalFrames:276,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702897807_CTX=gsap.context(()=>{_$W._mp_1702897807=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:.5,timeSlide2:1.8,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4794, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/smgm-en/,/slotted-microwave-guide-mini-smgm-sk/', 23),
(24, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/c8medej/\",ext:\"webp\",timelineUID:\"_mp_1702913265\",totalFrames:51,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702913265_CTX=gsap.context(()=>{_$W._mp_1702913265=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:2,timeSlide1:1.7,timeSlide2:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4800, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/powercom-en/,/powercom-485-sk/', 24),
(25, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/mh1349e/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702982049\",totalFrames:222,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702982049_CTX=gsap.context(()=>{_$W._mp_1702982049=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:.9,timeSlide2:2.1,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4806, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/apos-magnetic-touchless-en/,/apos-magnetic-touchless-sk/', 25),
(26, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/07j5299/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1702982363\",totalFrames:167,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702982363_CTX=gsap.context(()=>{_$W._mp_1702982363=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:2,timeSlide1:1.2,timeSlide2:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4810, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/apos-magnetic-gliding-en/,/apos-magnetic-sk/', 26),
(27, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/gkmk735/\",ext:\"webp\",timelineUID:\"_mp_1702982596\",totalFrames:118,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702982596_CTX=gsap.context(()=>{_$W._mp_1702982596=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:2,timeSlide1:1.8,timeSlide2:3.95},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4816, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/apos-optic-en/,/apos-optic-sk/', 27),
(28, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/2jeh2il/\",ext:\"webp\",timelineUID:\"_mp_1702982873\",totalFrames:51,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702982873_CTX=gsap.context(()=>{_$W._mp_1702982873=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:2,timeSlide1:1.8,timeSlide2:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4821, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/vcs1-en/,/riadiaci-system-vcs1/', 28),
(29, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/i24mahi/\",ext:\"webp\",timelineUID:\"_mp_1702983567\",totalFrames:52,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702983567_CTX=gsap.context(()=>{_$W._mp_1702983567=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:2,timeSlide1:1.8,timeSlide2:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4827, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/vcsx-en/,/modularne-ovladacie-prvky-vcsx/', 29),
(30, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/eeafala/\",ext:\"webp\",timelineUID:\"_mp_1702989478\",totalFrames:52,imgBreakpoints:{small:576,medium:768}});_$W._mp_1702989478_CTX=gsap.context(()=>{_$W._mp_1702989478=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:2,timeSlide1:1.85,timeSlide2:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4832, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/vcs-smg-safe-en/,/bezpecne-ovladanie-aplikacii-vcs-smg-safe/', 30),
(31, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/98hm5j1/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1703028531\",totalFrames:171,imgBreakpoints:{small:576,medium:768}});_$W._mp_1703028531_CTX=gsap.context(()=>{_$W._mp_1703028531=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:4,timeSlide1:1.4,timeSlide2:2.4,timeSlide3:3.4,timeSlide4:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4837, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/smart-collector-en/,/smart-collectors-sk/', 31),
(32, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/77cfdih/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1703032013\",totalFrames:281,imgBreakpoints:{small:576,medium:768}});_$W._mp_1703032013_CTX=gsap.context(()=>{_$W._mp_1703032013=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:2.2,timeSlide2:3.1,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4842, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/ertg-system-en/,/ertg-system-sk/', 32),
(33, 'window._mp_sequence_FGchFglHKzKeuxzqk=new window.MOTIONPAGE_FRONT.imageSequence({id:\"FGchFglHKzKeuxzqk\",canvasSelector:\"#mpAnimation\",largeImagesRoot:\"https://s-d-a.tech/wp-content/uploads/sequence/hd13ljc/\",ext:\"webp\",skipFrames:2,timelineUID:\"_mp_1703032255\",totalFrames:141,imgBreakpoints:{small:576,medium:768}});_$W._mp_1703032255_CTX=gsap.context(()=>{_$W._mp_1703032255=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",data:{numSlides:3,timeSlide1:1,timeSlide2:2,timeSlide3:3.9},onUpdate:function(){try{_mp_sequence_FGchFglHKzKeuxzqk.handleUpdate(this.progress())}catch(e){}},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4846, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/ems-system-en/,/ems-system-sk/', 33),
(36, 'window._mp_sequence_KEHNRANPSKJTJAMEZ = new window.MOTIONPAGE_FRONT.imageSequence({\"id\":\"KEHNRANPSKJTJAMEZ\",\"canvasSelector\":\"#mpAnimation\",\"largeImagesRoot\":\"https://s-d-a.tech/wp-content/uploads/sequence/i5e39g3/\",\"ext\":\"webp\",\"totalFrames\":141,\"skipFrames\":2,\"timelineUID\":\"_mp_1767957520\",\"dpr\":1.25});_$W._mp_1767957520_CTX=gsap.context(()=>{_$W._mp_1767957520=gsap.timeline().from(\"#mpAnimation\",{id:\"mpSequence\",numSlides:3,timeSlide1:1.1,timeSlide2:2.2,timeSlide3:3.5,data:{numSlides:3,timeSlide1:1.1,timeSlide2:2.2,timeSlide3:3.5},onUpdate:function(){let s=_mp_sequence_KEHNRANPSKJTJAMEZ;s&&\"handleUpdate\"in s&&s.handleUpdate(this.progress())},duration:4},0).yoyo(!0).repeat(-1).pause()});', 4657, 0, 1, 'ImageSequence,BypassReducedMotion', '', '/otvorene-systemy/,/open-en/,/open-conductor-system/', 36);

--
-- Kľúče pre exportované tabuľky
--

--
-- Indexy pre tabuľku `wp_Ekupa97M_motionpage_code`
--
ALTER TABLE `wp_Ekupa97M_motionpage_code`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pre exportované tabuľky
--

--
-- AUTO_INCREMENT pre tabuľku `wp_Ekupa97M_motionpage_code`
--
ALTER TABLE `wp_Ekupa97M_motionpage_code`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
